module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    // NOTE on worklets (SMS scan, ROADMAP Phase 2 workstream D): babel-preset-expo
    // auto-adds `react-native-worklets/plugin` because react-native-worklets is
    // installed (it ships with reanimated 4) — see babel-preset-expo
    // build/configs/expo.js. Do NOT add the plugin here manually or it runs twice.
    // Inlines the .sql migration files generated by drizzle-kit as strings so
    // they can be bundled into the app and run by useMigrations().
    plugins: [["inline-import", { extensions: [".sql"] }]],
  };
};
