module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    // Inlines the .sql migration files generated by drizzle-kit as strings so
    // they can be bundled into the app and run by useMigrations().
    plugins: [["inline-import", { extensions: [".sql"] }]],
  };
};
