// GENERATED by scripts/sync-bundled-manifests.ts — do not edit by hand.
// To change the bundled set, edit the allowlist in that script and re-run
// `bun run sync:manifests`. Each .json here is a byte-for-byte copy of the
// same file in the unmiser-extensions store repo (the source of truth).

import type { ManifestWithFixtures } from "@/lib/parser/types";

import airtelPaymentsBankBundle from "@/lib/parser/manifests/airtel-payments-bank.json";
import axisBankBundle from "@/lib/parser/manifests/axis-bank.json";
import bankOfBarodaBundle from "@/lib/parser/manifests/bank-of-baroda.json";
import credBundle from "@/lib/parser/manifests/cred.json";
import hdfcBankBundle from "@/lib/parser/manifests/hdfc-bank.json";
import iciciBankBundle from "@/lib/parser/manifests/icici-bank.json";
import iobBankBundle from "@/lib/parser/manifests/iob-bank.json";
import jiopayBundle from "@/lib/parser/manifests/jiopay.json";
import kotakBankBundle from "@/lib/parser/manifests/kotak-bank.json";
import pnbBankBundle from "@/lib/parser/manifests/pnb-bank.json";
import sbiBankBundle from "@/lib/parser/manifests/sbi-bank.json";
import sliceBundle from "@/lib/parser/manifests/slice.json";

// Default bundled parser plugins. The full community store (99+ banks) lives
// in the separate unmiser-extensions repo; each .json here is the same
// authorable bundle shape (see lib/parser/manifest.schema.json). JSON imports
// type fields as plain strings, so bundles are asserted to the
// runtime-validated ManifestWithFixtures shape (the engine zod-parses every
// manifest before use); fixtures are validated by lib/parser/engine.test.ts.
const jsonBundles = [
  airtelPaymentsBankBundle,
  axisBankBundle,
  bankOfBarodaBundle,
  credBundle,
  hdfcBankBundle,
  iciciBankBundle,
  iobBankBundle,
  jiopayBundle,
  kotakBankBundle,
  pnbBankBundle,
  sbiBankBundle,
  sliceBundle,
];

export const bundledParserBundles = jsonBundles.map(
  ({ manifest, fixtures }) => ({ manifest, fixtures }) as unknown as ManifestWithFixtures,
);
export const bundledParserManifests = bundledParserBundles.map((bundle) => bundle.manifest);
