/**
 * Bundled-manifest allowlist sync (ROADMAP Phase 2, workstream C).
 *
 * The unmiser-extensions store repo is the single source of truth for every
 * parser manifest. The app ships a small reach-selected subset for offline
 * cold-start (zero-network first parse) — NOT for coverage. This script:
 *
 *   1. copies each allowlisted store file byte-for-byte into
 *      lib/parser/manifests/ (no fork/drift),
 *   2. validates every copied bundle (zod schema + fixture run through the
 *      real engine) and fails loudly on any problem,
 *   3. regenerates lib/parser/manifests/index.ts.
 *
 * Run with:  bun run sync:manifests
 */

import { existsSync } from "node:fs";
import { copyFile, readFile, readdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

import { validateManifestFixtures } from "@/lib/parser/fixtures";
import { manifestBundleSchema } from "@/lib/parser/manifest-schema";
import type { ManifestWithFixtures } from "@/lib/parser/types";

/**
 * Allowlist of store filenames (in unmiser-extensions/manifests/) bundled into
 * the app. Reach-selected: India majors + dominant UPI/PPI wallets + the
 * original five. Everything else stays registry-only.
 */
const BUNDLED_MANIFEST_FILES = [
  // Original five (hardened on-device).
  "hdfc-bank.json",
  "iob-bank.json",
  "jiopay.json",
  "sbi-bank.json",
  "slice.json",
  // India majors.
  "icici-bank.json",
  "axis-bank.json",
  "kotak-bank.json",
  "pnb-bank.json",
  "bank-of-baroda.json",
  // High-reach payments bank / UPI wallet (paytm/phonepe not in store yet).
  "airtel-payments-bank.json",
  "cred.json",
] as const;

const APP_ROOT = path.resolve(import.meta.dirname, "..");
const STORE_MANIFESTS_DIR = path.resolve(APP_ROOT, "../unmiser-extensions/manifests");
const APP_MANIFESTS_DIR = path.join(APP_ROOT, "lib/parser/manifests");

function fail(message: string): never {
  console.error(`\nsync-bundled-manifests FAILED: ${message}`);
  process.exit(1);
}

function importNameFor(file: string): string {
  const base = file.replace(/\.json$/, "");
  const camel = base.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
  return `${camel}Bundle`;
}

async function validateStoreFile(storePath: string, file: string): Promise<void> {
  const raw = await readFile(storePath, "utf8");
  let json: unknown;
  try {
    json = JSON.parse(raw);
  } catch (error) {
    fail(`${file}: invalid JSON — ${String(error)}`);
  }

  const parsed = manifestBundleSchema.safeParse(json);
  if (!parsed.success) {
    fail(`${file}: schema validation failed —\n${parsed.error.message}`);
  }

  const fixtureFailures = validateManifestFixtures(parsed.data as ManifestWithFixtures);
  if (fixtureFailures.length > 0) {
    const detail = fixtureFailures.map((f) => `  [${f.fixture}] ${f.message}`).join("\n");
    fail(`${file}: ${fixtureFailures.length} fixture failure(s) —\n${detail}`);
  }
}

function renderIndexTs(files: readonly string[]): string {
  const sorted = [...files].sort();
  const imports = sorted
    .map((file) => `import ${importNameFor(file)} from "@/lib/parser/manifests/${file}";`)
    .join("\n");
  const names = sorted.map(importNameFor).join(", ");

  return `// GENERATED by scripts/sync-bundled-manifests.ts — do not edit by hand.
// To change the bundled set, edit the allowlist in that script and re-run
// \`bun run sync:manifests\`. Each .json here is a byte-for-byte copy of the
// same file in the unmiser-extensions store repo (the source of truth).

import type { ManifestWithFixtures } from "@/lib/parser/types";

${imports}

// Default bundled parser plugins. The full community store (99+ banks) lives
// in the separate unmiser-extensions repo; each .json here is the same
// authorable bundle shape (see lib/parser/manifest.schema.json). JSON imports
// type fields as plain strings, so bundles are asserted to the
// runtime-validated ManifestWithFixtures shape (the engine zod-parses every
// manifest before use); fixtures are validated by lib/parser/engine.test.ts.
const jsonBundles = [${names}];

export const bundledParserBundles = jsonBundles.map(
  ({ manifest, fixtures }) => ({ manifest, fixtures }) as unknown as ManifestWithFixtures,
);
export const bundledParserManifests = bundledParserBundles.map((bundle) => bundle.manifest);
`;
}

async function main(): Promise<void> {
  if (!existsSync(STORE_MANIFESTS_DIR)) {
    fail(`store manifests dir not found: ${STORE_MANIFESTS_DIR}`);
  }

  // Validate everything before touching the app dir (all-or-nothing).
  for (const file of BUNDLED_MANIFEST_FILES) {
    const storePath = path.join(STORE_MANIFESTS_DIR, file);
    if (!existsSync(storePath)) {
      fail(`allowlisted file missing from store: ${storePath}`);
    }
    await validateStoreFile(storePath, file);
    console.log(`validated  ${file}`);
  }

  // Remove stale .json files no longer on the allowlist.
  const allowed = new Set<string>(BUNDLED_MANIFEST_FILES);
  for (const existing of await readdir(APP_MANIFESTS_DIR)) {
    if (existing.endsWith(".json") && !allowed.has(existing)) {
      await unlink(path.join(APP_MANIFESTS_DIR, existing));
      console.log(`removed    ${existing} (not on allowlist)`);
    }
  }

  for (const file of BUNDLED_MANIFEST_FILES) {
    await copyFile(path.join(STORE_MANIFESTS_DIR, file), path.join(APP_MANIFESTS_DIR, file));
    console.log(`copied     ${file}`);
  }

  await writeFile(path.join(APP_MANIFESTS_DIR, "index.ts"), renderIndexTs(BUNDLED_MANIFEST_FILES));
  console.log(`wrote      index.ts (${BUNDLED_MANIFEST_FILES.length} bundled manifests)`);
}

await main();
